### ISSUE TITLE
fas报错 readme里的方法无效 Mac下面

### ISSUE THREAD

**Issue by vz8946** [ibbd-dev/fastapi-start#29]
`
$ fas           
Traceback (most recent call last):
  File "/Users/liheng/.pyenv/versions/3.9.6/envs/fastapistart/bin/fas", line 33, in <module>
    sys.exit(load_entry_point('fastapi-start==0.6.8', 'console_scripts', 'fas')())
  File "/Users/liheng/.pyenv/versions/3.9.6/envs/fastapistart/bin/fas", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/Users/liheng/.pyenv/versions/3.9.6/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/Users/liheng/.pyenv/versions/3.9.6/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: fastapi-start
(fastapistart) (base) 
`

**Comment by cyy0523xc** [comment]
你是怎么安装的
